sudo: required
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install:
- npm install -g gitbook-cli
- npm install -g markdownlint-cli
- sudo pip install -U requests
- sudo pip install -U qsctl
- sudo apt-get update
- sudo apt-get install -y xvfb
- sudo apt-get install -y imagemagick
- sudo apt-get install -y calibre
- sudo apt-get install language-pack-zh-hans  language-pack-zh-hans-base 

before_script:
- export FILENAME="_book/qingcloud-appcenter-developer-guide"
script:
- markdownlint --config markdownlint.conf.json developer/
- gitbook install
- gitbook build . $FILENAME
- xvfb-run gitbook pdf . $FILENAME.pdf
- gitbook epub . $FILENAME.epub

- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_4812bbd1d0bc_key -iv $encrypted_4812bbd1d0bc_iv
  -in config.yaml.enc -out config.yaml -d ;qsctl
  sync _book/qingcloud-appcenter-developer-guide/ qs://appcenter-docs/developer-guide/
  --config config.yaml;qsctl
  cp -f _book/qingcloud-appcenter-developer-guide.pdf qs://appcenter-docs/developer-guide/
  --config config.yaml;qsctl
  cp -f _book/qingcloud-appcenter-developer-guide.epub qs://appcenter-docs/developer-guide/
  --config config.yaml;fi
notifications:
  slack:
    secure: uOnKljnxLH5YApJ/mdPJurGYmOvLibIENVEgaln8ibAp+2xeHTJ9QoKSRJQjGB1Dl9EBB6pvu/mSQsE7ywsH9xHMG8gUSn6KlEwuQ1vUhdY3hwTmRxDcfIxsguFCGXGP6TQZqz28IoD+7oLr+JYV5c8YEW50vQtfSxnf/p6LWzNZEKpoH2OxoHcM44oZv5py5FQQHXL40TkOTQeSZndYUjjsWWZWsiM8G4Um5W7WPTZAQt+aFFCTKKzy4AEI9dpUYQaQjigpz6rsCyVmxEAXLSCveRt5Kh6f9/72a72tPzNuyiqi8qw1mFa5xc9duEHDx6LWhtg4F0nChwRTVx4CjrL4SidP70ydz28oiiFyER6HofQNeLzaS9TnX4pzzsjOwGK3e4u52bq9lsJvNT902YgMChtjekNHN/ZMISWZoLPrcAT/heXhfrjP+9NHI7UJt8zNcVFVkfac86tJyiu+pEB+gD4QLH3a8q0cVM62o1/adKZ88r5CvM2Uf76Ug6cTo8ju1AbHzAj88HZe42ZSC31g7tcOqYRoT3k3TSxY1J86quHAmAcp3BUYynC1IQtT18w+oq9shM8Yn6md52wVrU8pO7Ffxqgg1c1IhZErMGbaZc/lvxfbvg8RbLF1itKR1g+1vnRi3gH1RhmoKeH9dqyGdKOtkzLqWC73ccXn7qU=
