#!/bin/sh
#
# Copyright (C) 2016 Yunify Inc.
#
# Script to manage confd service for Debian

### BEGIN INIT INFO
# Provides:        confd
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: manage confd daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

PROG="confd"
PROG_PATH=/opt/qingcloud/app-agent
PROG_BIN=$PROG_PATH/bin/$PROG
PIDFILE=$PROG_PATH/run/$PROG.pid

if ! [ -f $PROG_BIN ]; then
  echo "$PROG_BIN binary not found."
  exit 5
fi

start() {
  log_daemon_msg "Starting $PROG server: "
  start-stop-daemon --start --quiet --oknodo --background --pidfile $PIDFILE --make-pidfile --startas /bin/bash -- -c "exec $PROG_BIN >> $PROG_PATH/log/$PROG.log 2>&1"
  status=$?
  log_end_msg $status
}

stop() {
  log_begin_msg "Stopping $PROG server: "
  start-stop-daemon --stop --pidfile "$PIDFILE"
  status=$?
  
  if [ -f $PIDFILE ]; then
    rm $PIDFILE
  fi
  
  log_end_msg $status
}

restart() {
    stop
    start
}

status() {
  status_of_proc -p "$PIDFILE" "$PROG_BIN" $PROG
}

case "$1" in
  start)   start;;
  stop)    stop;;
  restart) restart;;
  status)  status;;
  *)       echo "Usage: $0 {start|stop|restart|status}"
           RETVAL=2;;
esac
exit $RETVAL
